# Generated by Django 5.0.6 on 2024-07-01 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_rename_data_atualizacao_categoria_atualizado_em_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='embalagem',
            old_name='name',
            new_name='nome',
        ),
    ]
